# general settings
name: train_PLKSR_DIV2K_X4_64_12_0.25_13
use_amp: true
model_type: ESRModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: /home/dslisleedh/SAFMN/datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    dataroot_lq: /home/dslisleedh/SAFMN/datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: lmdb

    gt_size: 384
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: /home/dslisleedh/SAFMN/datasets/Urban100/HR
    dataroot_lq: /home/dslisleedh/SAFMN/datasets/Urban100/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

# network structures
network_g:
  type: PLKSR
  dim: 64
  n_blocks: 12
  kernel_size: 13
  split_ratio: 0.25
  ccm_type: DCCM
  lk_type: PLK
  use_ea: false
  upscaling_factor: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  # ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [100000, 200000, 300000, 400000, 425000]
    gamma: 0.5

  total_iter: 450000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 1000
  save_img: False
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
